spring:
  application:
    name: hello-spring-cloud-service-admin
  zipkin:
    base-url: http://localhost:8769
  boot:
    admin:
      client:
        url: http://localhost:8770

server:
  port: 8762

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/