spring:
  application:
    name: hello-spring-cloud-zuul
  zipkin:
    base-url: http://localhost:8769
  boot:
    admin:
      client:
        url: http://localhost:8770

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-feign
