spring:
  application:
    name: hello-spring-cloud-zipkin
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  boot:
    admin:
      client:
        url: http://localhost:8770
server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false