spring:
  application:
    name: hello-spring-cloud-admin
  #main:
   # allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  zipkin:
    base-url: http://localhost:8769



server:
  port: 8770

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]
