spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  cloud:
    config:
      uri: http://localhost:8888
      name: web-admin-feign
      profile: prod
      label: master
  zipkin:
    base-url: http://localhost:8769
  boot:
    admin:
      client:
        url: http://localhost:8770
